version: '3'

services:
  # Серверная часть (FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./app.db:/app/app.db
    environment:
      - GIGACHAT_AUTH_TOKEN=${GIGACHAT_AUTH_TOKEN}
      - GIGACHAT_CLIENT_SECRET=${GIGACHAT_CLIENT_SECRET}
      - SALUTE_SPEECH_AUTH_TOKEN=${SALUTE_SPEECH_AUTH_TOKEN}
      - SALUTE_SPEECH_SCOPE=${SALUTE_SPEECH_SCOPE}
      - FFMPEG_PATH=/usr/bin/ffmpeg

  # Клиентская часть (React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
